# Generated by Django 4.1.13 on 2024-12-19 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='classification_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='classification_value',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(choices=[('BBOX', 'Bounding Box'), ('POLYGON', 'Polygon'), ('POINT', 'Point'), ('LINE', 'Polyline'), ('MASK', 'Mask'), ('CLASSIFICATION', 'Classification')], default='BBOX', max_length=20),
        ),
        migrations.AddField(
            model_name='annotation',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='annotationproject',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image')], default='IMAGE', max_length=50),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('classification_type', models.CharField(choices=[('RADIO', 'Radio'), ('CHECKLIST', 'Checklist'), ('TEXT', 'Text')], max_length=20)),
                ('value', models.JSONField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='annotation.annotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
