# Generated by Django 4.1.13 on 2024-12-21 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_rename_classification_name_annotation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=255)),
                ('annotation_name', models.CharField(max_length=255)),
                ('annotation_type', models.CharField(max_length=50)),
                ('annotation_data', models.JSONField()),
                ('image_file', models.ImageField(upload_to='exported_annotations/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(choices=[('bounding_box', 'Bounding Box'), ('polygon', 'Polygon'), ('point', 'Point'), ('LINE', 'Polyline'), ('MASK', 'Mask'), ('CLASSIFICATION', 'Classification')], default='BBOX', max_length=20),
        ),
    ]
