# Generated by Django 4.1.13 on 2024-12-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_exportedannotation_alter_annotation_annotation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationproject',
            name='lb_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(choices=[('bounding_box', 'Bounding Box'), ('polygon', 'Polygon'), ('point', 'Point'), ('LINE', 'Polyline'), ('MASK', 'Mask'), ('CLASSIFICATION', 'Classification')], default='bounding_box', max_length=20),
        ),
    ]
